"""empty message

Revision ID: 5251c291bf2b
Revises: 
Create Date: 2024-03-22 16:39:58.371355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5251c291bf2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_ranking', sa.String(length=100), nullable=True),
    sa.Column('job_index', sa.Integer(), nullable=True),
    sa.Column('job_rating', sa.Integer(), nullable=True),
    sa.Column('job_website', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('job_company', sa.String(length=100), nullable=True),
    sa.Column('job_company_type', sa.String(length=100), nullable=True),
    sa.Column('job_company_sector', sa.String(length=100), nullable=True),
    sa.Column('job_country', sa.String(length=100), nullable=True),
    sa.Column('job_country_code', sa.String(length=100), nullable=True),
    sa.Column('job_city', sa.String(length=100), nullable=True),
    sa.Column('job_summary', sa.String(length=300), nullable=True),
    sa.Column('job_date', sa.String(length=100), nullable=True),
    sa.Column('job_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
